version: '3.8'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    networks:
      - app-network

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www
    ports:
      - 8000:8000
    networks:
      - app-network

  mobile:
    build: ./mobile
    volumes:
      - ./mobile:/app
    ports:
      - 19006:19006
      - 19001:19001
    networks:
      - app-network
  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: patyurui
      POSTGRES_PASSWORD: patyurui
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge